### ISSUE TITLE
Integrating slinky demos

### ISSUE THREAD

**Issue by AlexITC** [oyvindberg/st-material-ui-demo#3]
I have ported the demos to slinky (https://github.com/wiringbits/st-material-ui-demo-slinky), it would be ideal to integrate those into this repository, still, the vite settings are tied to a single module instead of multiple ones. I haven't dig into this, if you have anything working, I'd be happy to try it.

An alternative way would be to just create two independent directories.

**Comment by oyvindberg** [comment]
I'm inclined to keep them as two repositories for now, just because it's less work and there is very little code to share. I mean it's all very similar, but it's all different

**Comment by AlexITC** [comment]
Sounds good, thanks for reviewing this.
